### ISSUE TITLE
Intergas_reader_wire_schema.jpg - Intergas voltage incorrect

### ISSUE THREAD

**Issue by gaardiolor** [keesma/Intergas-Central-Heating-Monitor-Homie#2]
Hi Kees,

Intergas_reader_wire_schema.jpg lists the Intergas port at the top as being +3.3V, however mine reads (close to) 5V.

**Comment by keesma** [comment]
I have asked the creator of the wire scheme to update it.

**Comment by keesma** [comment]
The creator of the scheme says his intergas report 3.3V so it is probably dependent on the type.
